baseURL = 'https://asimondev.github.io/'
languageCode = 'en-us'
title = "Andrej Simon's GitHub Pages"
theme = "hextra"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    pageRef = "/"
    weight = 1

  [[menu.main]]
    identifier = "tools"
    name = "Tools"
    pageRef = "/docs"
    weight = 2

  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    pageRef = "/blog"
    weight = 3

  [[menu.main]]
    identifier = "about"
    name = "About"
    pageRef = "/about"
    weight = 4

  [[menu.main]]
    name = "Search"
    weight = 5
    [menu.main.params]
      type = "search"

  [[menu.main]]
    name = "GitHub"
    weight = 6
    url = "https://github.com/asimondev"
    [menu.main.params]
      icon = "github"

[params]
  description = "Modern, responsive, batteries-included Hugo theme for creating beautiful static websites."

  [params.navbar]
    displayTitle = true
    displayLogo = true
    width = "wide"
  
    [params.navbar.logo]
      path = "images/logo.svg"
      dark = "images/logo-dark.svg"
      # width = 40
      # height = 20
      # link = "/"

  [params.page]
    width = "normal"  # full (100%), wide (90rem), normal (1280px)

  [params.theme]
    default = "system"  # light | dark | system
    displayToggle = true

  [params.footer]
    enable = true
    displayCopyright = true
    displayPoweredBy = true
    width = "normal"

  displayUpdatedDate = true
  dateFormat = "January 2, 2006"

  [params.search]
    enable = true
    type = "flexsearch"
    
    [params.search.flexsearch]
      index = "content"  # content | summary | heading | title
      tokenize = "forward"  # full | forward | reverse | strict

  [params.editURL]
    enable = false

  [params.blog.list]
    displayTags = true
    sortBy = "date"  # date | lastmod | publishDate | title | weight
    sortOrder = "desc"  # or "asc"

  [params.highlight.copy]
    enable = true
    display = "hover"  # hover | always

  [params.comments]
    enable = false
